name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm ci
          cd backend && npm ci
          cd ../frontend && npm ci
          cd ..
      
      - name: Set up PostgreSQL
        env:
          PGPASSWORD: test
        run: |
          psql -h localhost -U test -d test -c "CREATE USER test WITH PASSWORD 'test' SUPERUSER;"
          psql -h localhost -U test -d test -c "ALTER DATABASE test OWNER TO test;"
        # Continue on error in case the user already exists
        continue-on-error: true
      
      - name: Run Backend Tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          NODE_ENV: test
        run: npm test
      
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      - name: Run Simulation Tests
        run: npm test -- task-1/simulation.test.ts
